### ISSUE TITLE
Admin is not able to create event

### ISSUE THREAD

**Issue by kimbeavis-work** [andyperlitch/tcf-client#7]
Server error code
` message: '\n' +
    'Invalid `prisma.event.create()` invocation in\n' +
    '/Users/kimbeavis/Documents/TCF/tcf-server/src/graphql/resolvers/events/createEvent.ts:15:23\n' +
    '\n' +
    '  12   throw new Error("Event data is required");\n' +
    '  13 }\n' +
    '  14 const { slug, name, description, date, location } = data;\n' +
    '→ 15 return prisma.event.create(\n' +
    'Unique constraint failed on the fields: (`slug`)',
  locations: [ { line: 2, column: 3 } ],
  path: [ 'createEvent' ],
  extensions: {
    code: 'INTERNAL_SERVER_ERROR',
    stacktrace: [
      'PrismaClientKnownRequestError: ',
      'Invalid `prisma.event.create()` invocation in',
      '/Users/kimbeavis/Documents/TCF/tcf-server/src/graphql/resolvers/events/createEvent.ts:15:23',
      '',
      '  12   throw new Error("Event data is required");',
      '  13 }',
      '  14 const { slug, name, description, date, location } = data;',
      '→ 15 return prisma.event.create(',
      'Unique constraint failed on the fields: (`slug`)',
      '    at $n.handleRequestError (/Users/kimbeavis/Documents/TCF/tcf-server/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7315)',
      '    at $n.handleAndLogRequestError (/Users/kimbeavis/Documents/TCF/tcf-server/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)',
      '    at $n.request (/Users/kimbeavis/Documents/TCF/tcf-server/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)',
      '    at async l (/Users/kimbeavis/Documents/TCF/tcf-server/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)'
    ]
  }
}`

**Comment by andyperlitch** [comment]
Hmm... just tried reproducing locally and in prod and could not... @kimbeavis-work can you try again?

**Comment by kimbeavis-work** [comment]
I just tried again and it works \:D/
